/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 * @format
 */

'use strict';

import type {RNTesterModule} from '../../types/RNTesterTypes';

import {installStylesheet} from '../../astryx/css';
// Vendored shadcn/ui sources, UNMODIFIED, running on: the stylesheet engine
// (their Tailwind build), the Radix shims (their primitives), the intrinsics
// runtime (their markup). $FlowFixMe on each: Metro resolves, Flow cannot.
// $FlowFixMe[cannot-resolve-module]
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '../../shadcn/ui/accordion';
// $FlowFixMe[cannot-resolve-module]
import {Alert, AlertDescription, AlertTitle} from '../../shadcn/ui/alert';
// $FlowFixMe[cannot-resolve-module]
import {Badge} from '../../shadcn/ui/badge';
// $FlowFixMe[cannot-resolve-module]
import {Button} from '../../shadcn/ui/button';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {Card, CardContent, CardDescription, CardHeader, CardTitle} from '../../shadcn/ui/card';
// $FlowFixMe[cannot-resolve-module]
import {Checkbox} from '../../shadcn/ui/checkbox';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger} from '../../shadcn/ui/dialog';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger} from '../../shadcn/ui/dropdown-menu';
// $FlowFixMe[cannot-resolve-module]
import {Progress} from '../../shadcn/ui/progress';
// $FlowFixMe[cannot-resolve-module]
import {Skeleton} from '../../shadcn/ui/skeleton';
// $FlowFixMe[cannot-resolve-module]
import {Switch} from '../../shadcn/ui/switch';
// $FlowFixMe[cannot-resolve-module]
import {Tabs, TabsContent, TabsList, TabsTrigger} from '../../shadcn/ui/tabs';
import shadcnGlobals from '../../shadcn/globals.css';
// $FlowFixMe[cannot-resolve-module] generated by shadcn/generate.sh
import tailwindCss from '../../shadcn/tailwind.generated.css';
import * as React from 'react';
import {useState} from 'react';
import {ScrollView} from 'react-native';

installStylesheet(shadcnGlobals);
installStylesheet(tailwindCss);

function Demo(): React.Node {
  const [checked, setChecked] = useState(false);
  const [lastAction, setLastAction] = useState('none');
  return (
    <div className="p-4 bg-background">
      <Card className="mb-4">
        <CardHeader>
          <CardTitle>shadcn/ui on React Native</CardTitle>
          <CardDescription>
            Unmodified sources; Tailwind build through the stylesheet engine;
            Radix through the shims.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-row gap-2">
          <Badge>badge</Badge>
          <Badge variant="secondary">secondary</Badge>
          <Badge variant="destructive">destructive</Badge>
          <Badge variant="outline">outline</Badge>
        </CardContent>
      </Card>

      <div className="mb-4 flex flex-row gap-2">
        <Button onClick={() => setLastAction('default')}>Default</Button>
        <Button variant="secondary" onClick={() => setLastAction('secondary')}>
          Secondary
        </Button>
        <Button variant="destructive">Destructive</Button>
        <Button variant="outline">Outline</Button>
      </div>

      <Alert className="mb-4">
        <AlertTitle>Heads up (last: {lastAction})</AlertTitle>
        <AlertDescription>
          This alert is the vendored alert.tsx, styled by its own classes.
        </AlertDescription>
      </Alert>

      <div className="mb-4 flex flex-row items-center gap-3">
        <Switch checked={checked} onCheckedChange={setChecked} />
        <Checkbox checked={checked} onCheckedChange={setChecked} />
        <Progress value={checked ? 80 : 30} className="w-40" />
        <Skeleton className="h-4 w-16" />
      </div>

      <Tabs defaultValue="account" className="mb-4">
        <TabsList>
          <TabsTrigger value="account">Account</TabsTrigger>
          <TabsTrigger value="password">Password</TabsTrigger>
        </TabsList>
        <TabsContent value="account">Account settings panel.</TabsContent>
        <TabsContent value="password">Password settings panel.</TabsContent>
      </Tabs>

      <div className="mb-4 flex flex-row gap-2">
        <Dialog>
          <DialogTrigger asChild>
            <Button variant="outline">Open dialog</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>shadcn dialog</DialogTitle>
              <DialogDescription>
                dialog.tsx over the Radix shim over the top layer.
              </DialogDescription>
            </DialogHeader>
          </DialogContent>
        </Dialog>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="secondary">Menu</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>Actions</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem onSelect={() => setLastAction('copy')}>
              Copy
            </DropdownMenuItem>
            <DropdownMenuItem onSelect={() => setLastAction('share')}>
              Share
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <Accordion type="single" collapsible className="mb-4">
        <AccordionItem value="a">
          <AccordionTrigger>Is it accessible?</AccordionTrigger>
          <AccordionContent>
            Yes — the shims carry the aria surface.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="b">
          <AccordionTrigger>Is it styled?</AccordionTrigger>
          <AccordionContent>
            By its own Tailwind classes, resolved by the fork.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}

function ShadcnExample(): React.Node {
  return (
    <ScrollView style={{flex: 1}}>
      <Demo />
    </ScrollView>
  );
}

export default {
  title: 'shadcn/ui',
  category: 'UI',
  description:
    'Vendored, unmodified shadcn/ui components: Tailwind classes through ' +
    'the stylesheet engine, Radix primitives through the shims.',
  examples: [
    {
      title: 'shadcn/ui',
      render(): React.Node {
        return <ShadcnExample />;
      },
    },
  ],
} as RNTesterModule;
