/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 * @format
 */

'use strict';

import type {RNTesterModule} from '../../types/RNTesterTypes';

import {installStylesheet} from '../../astryx/css';
import shadcnGlobals from '../../shadcn/globals.css';
// $FlowFixMe[cannot-resolve-module] generated by shadcn/generate.sh
import tailwindCss from '../../shadcn/tailwind.generated.css';
// Vendored shadcn/ui sources, UNMODIFIED, running on: the stylesheet engine
// (their Tailwind build), the Radix shims (their primitives), the intrinsics
// runtime (their markup). $FlowFixMe on each: Metro resolves, Flow cannot.
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {Accordion, AccordionContent, AccordionItem, AccordionTrigger} from '../../shadcn/ui/accordion';
// $FlowFixMe[cannot-resolve-module]
import {Alert, AlertDescription, AlertTitle} from '../../shadcn/ui/alert';
// $FlowFixMe[cannot-resolve-module]
import {Badge} from '../../shadcn/ui/badge';
// $FlowFixMe[cannot-resolve-module]
import {Button} from '../../shadcn/ui/button';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle} from '../../shadcn/ui/card';
// $FlowFixMe[cannot-resolve-module]
import {Checkbox} from '../../shadcn/ui/checkbox';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger} from '../../shadcn/ui/dialog';
// prettier-ignore
// $FlowFixMe[cannot-resolve-module]
import {DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger} from '../../shadcn/ui/dropdown-menu';
// $FlowFixMe[cannot-resolve-module]
import {Label} from '../../shadcn/ui/label';
// $FlowFixMe[cannot-resolve-module]
import {Progress} from '../../shadcn/ui/progress';
// $FlowFixMe[cannot-resolve-module]
import {RadioGroup, RadioGroupItem} from '../../shadcn/ui/radio-group';
// $FlowFixMe[cannot-resolve-module]
import {Separator} from '../../shadcn/ui/separator';
// $FlowFixMe[cannot-resolve-module]
import {Skeleton} from '../../shadcn/ui/skeleton';
// $FlowFixMe[cannot-resolve-module]
import {Switch} from '../../shadcn/ui/switch';
// $FlowFixMe[cannot-resolve-module]
import {Tabs, TabsContent, TabsList, TabsTrigger} from '../../shadcn/ui/tabs';
// $FlowFixMe[cannot-resolve-module]
import {Toggle} from '../../shadcn/ui/toggle';
import {DemoSection} from './DemoSection';
import * as React from 'react';
import {useState} from 'react';

installStylesheet(shadcnGlobals);
installStylesheet(tailwindCss);

// Two different problems, two different tools.
//
// A BUTTON should grow to clear the 44pt iOS minimum, so it takes a
// className — the consumer-override path these components are built for,
// resolved through cn().
const TOUCH = 'min-h-11 min-w-11';
// A SWITCH or CHECKBOX must NOT grow: its size is its design (44x24 and
// 16x16, measured against Safari), and stretching it to 44pt square turned
// the switch into a circle and the checkbox into a slab. Their touch target
// grows instead of their box — which is what hitSlop is for, and what a web
// page would do with a padded <label>.
//
// hitSlop is clipped by ancestor bounds: UIKit stops descending as soon as a
// point falls outside a parent, so slop hanging outside the row is slop that
// never gets hit-tested. The row therefore has to be at least as tall as the
// target it is meant to contain — hence TOUCH_ROW below. Sideways the slop
// stays inside half the 16pt gap so two neighbouring controls never claim
// the same point.
const TOUCH_SLOP = {top: 14, bottom: 14, left: 8, right: 8};
// A row that gives its controls somewhere to put their slop.
const TOUCH_ROW = 'flex flex-row flex-wrap items-center gap-4 min-h-11';

function ButtonsSection(): React.Node {
  const [lastAction, setLastAction] = useState('none');
  return (
    <DemoSection
      title="Button"
      description="Six variants from one cva() call. The demo adds a 44pt minimum through className — the consumer-override path the components are built for."
      code={`import {Button} from '@/components/ui/button';

<Button className="min-h-11 min-w-11">Default</Button>
<Button variant="secondary">Secondary</Button>
<Button variant="destructive">Destructive</Button>
<Button variant="outline">Outline</Button>
<Button variant="ghost">Ghost</Button>
<Button variant="link">Link</Button>`}>
      <div className="flex flex-row flex-wrap gap-2">
        <Button className={TOUCH} onClick={() => setLastAction('default')}>
          Default
        </Button>
        <Button
          className={TOUCH}
          variant="secondary"
          onClick={() => setLastAction('secondary')}>
          Secondary
        </Button>
        <Button
          className={TOUCH}
          variant="destructive"
          onClick={() => setLastAction('destructive')}>
          Destructive
        </Button>
        <Button
          className={TOUCH}
          variant="outline"
          onClick={() => setLastAction('outline')}>
          Outline
        </Button>
        <Button
          className={TOUCH}
          variant="ghost"
          onClick={() => setLastAction('ghost')}>
          Ghost
        </Button>
        <Button
          className={TOUCH}
          variant="link"
          onClick={() => setLastAction('link')}>
          Link
        </Button>
      </div>
      <span className="mt-2 block text-sm text-muted-foreground">
        Last pressed: {lastAction}
      </span>
    </DemoSection>
  );
}

function BadgeSection(): React.Node {
  return (
    <DemoSection
      title="Badge"
      description="Inline pills — the layout that proved cn() must group by CSS axis, not by class-name prefix (`flex` is display, `flex-row` is direction)."
      code={`<div className="flex flex-row flex-wrap gap-2">
  <Badge>badge</Badge>
  <Badge variant="secondary">secondary</Badge>
  <Badge variant="destructive">destructive</Badge>
  <Badge variant="outline">outline</Badge>
</div>`}>
      <div className="flex flex-row flex-wrap gap-2">
        <Badge>badge</Badge>
        <Badge variant="secondary">secondary</Badge>
        <Badge variant="destructive">destructive</Badge>
        <Badge variant="outline">outline</Badge>
      </div>
    </DemoSection>
  );
}

function CardSection(): React.Node {
  const [lastAction, setLastAction] = useState('none');
  return (
    <DemoSection
      title="Card"
      description="Header, content and footer composition; every colour is an hsl(var(--token)) that flips with the OS appearance."
      code={`<Card>
  <CardHeader>
    <CardTitle>Deploy</CardTitle>
    <CardDescription>Ship the current branch.</CardDescription>
  </CardHeader>
  <CardContent>Last button pressed: {lastAction}</CardContent>
  <CardFooter><Button>Deploy</Button></CardFooter>
</Card>`}>
      <Card>
        <CardHeader>
          <CardTitle>Deploy</CardTitle>
          <CardDescription>Ship the current branch.</CardDescription>
        </CardHeader>
        <CardContent>
          <span className="text-sm text-muted-foreground">
            Last button pressed: {lastAction}
          </span>
        </CardContent>
        <CardFooter>
          <Button className={TOUCH} onClick={() => setLastAction('deploy')}>
            Deploy
          </Button>
        </CardFooter>
      </Card>
    </DemoSection>
  );
}

function AlertSection(): React.Node {
  return (
    <DemoSection
      title="Alert"
      description="Its spacing comes entirely from utilities — which is why the globals sheet carries the part of Tailwind's preflight that zeroes heading margins."
      code={`<Alert>
  <AlertTitle>Heads up</AlertTitle>
  <AlertDescription>Styled by alert.tsx's own classes.</AlertDescription>
</Alert>

<Alert variant="destructive">…</Alert>`}>
      <Alert className="mb-3">
        <AlertTitle>Heads up</AlertTitle>
        <AlertDescription>
          This is the vendored alert.tsx, styled by its own classes.
        </AlertDescription>
      </Alert>
      <Alert variant="destructive">
        <AlertTitle>Destructive</AlertTitle>
        <AlertDescription>The variant's colours applied.</AlertDescription>
      </Alert>
    </DemoSection>
  );
}

function FormControlsSection(): React.Node {
  const [checked, setChecked] = useState(false);
  const [plan, setPlan] = useState('pro');
  return (
    <DemoSection
      title="Form controls"
      description="Switch, Checkbox and RadioGroup. Their boxes keep the sizes shadcn designed (44x24 and 16x16, matching Safari); the 44pt touch minimum comes from hitSlop plus a row tall enough to hold it, not from stretching the controls."
      code={`<Switch checked={checked} onCheckedChange={setChecked} />
<Checkbox checked={checked} onCheckedChange={setChecked} />

<RadioGroup value={plan} onValueChange={setPlan}>
  <RadioGroupItem value="free" /> <Label>Free</Label>
  <RadioGroupItem value="pro" />  <Label>Pro</Label>
</RadioGroup>`}>
      <div className={TOUCH_ROW}>
        <Switch
          hitSlop={TOUCH_SLOP}
          checked={checked}
          onCheckedChange={setChecked}
        />
        <Checkbox
          hitSlop={TOUCH_SLOP}
          checked={checked}
          onCheckedChange={setChecked}
        />
        <Label>{checked ? 'Subscribed' : 'Not subscribed'}</Label>
      </div>
      {/* The other state, statically, so both of a control's looks are on
          screen at once — this screen is a fidelity instrument as much as a
          demo, and a capture can only compare what it can see. */}
      <div className={TOUCH_ROW}>
        <Switch checked={true} />
        <Checkbox checked={true} />
        <Label>Checked twins</Label>
      </div>
      <Separator className="my-4" />
      <RadioGroup value={plan} onValueChange={setPlan}>
        <div className={TOUCH_ROW}>
          <RadioGroupItem hitSlop={TOUCH_SLOP} value="free" />
          <Label>Free</Label>
          <RadioGroupItem hitSlop={TOUCH_SLOP} value="pro" />
          <Label>Pro — “{plan}” selected</Label>
        </div>
      </RadioGroup>
    </DemoSection>
  );
}

function ProgressSection(): React.Node {
  const [pressed, setPressed] = useState(false);
  return (
    <DemoSection
      title="Progress, Skeleton, Toggle"
      description="Progress translates its indicator by percentage; Skeleton pulses on the renderer's animation engine. Pressing the Toggle drives the Progress value."
      code={`<Progress value={pressed ? 80 : 30} />
<Skeleton className="h-4 w-24" />
<Toggle className="min-h-11" pressed={pressed} onPressedChange={setPressed}>
  Bold
</Toggle>`}>
      <Progress className="mb-4" value={pressed ? 80 : 30} />
      <div className="flex flex-row flex-wrap items-center gap-3">
        <Skeleton className="h-4 w-24" />
        <Skeleton className="h-4 w-16" />
        <Toggle className={TOUCH} pressed={pressed} onPressedChange={setPressed}>
          Bold
        </Toggle>
      </div>
    </DemoSection>
  );
}

function TabsSection(): React.Node {
  return (
    <DemoSection
      title="Tabs"
      description="Only the active panel mounts; the trigger's active styling is a data-[state=active] rule."
      code={`<Tabs defaultValue="account">
  <TabsList>
    <TabsTrigger value="account">Account</TabsTrigger>
    <TabsTrigger value="password">Password</TabsTrigger>
  </TabsList>
  <TabsContent value="account">Account settings panel.</TabsContent>
  <TabsContent value="password">Password settings panel.</TabsContent>
</Tabs>`}>
      <Tabs defaultValue="account">
        <TabsList>
          <TabsTrigger className={TOUCH} value="account">
            Account
          </TabsTrigger>
          <TabsTrigger className={TOUCH} value="password">
            Password
          </TabsTrigger>
        </TabsList>
        <TabsContent value="account">
          <span className="text-sm text-muted-foreground">
            Account settings panel.
          </span>
        </TabsContent>
        <TabsContent value="password">
          <span className="text-sm text-muted-foreground">
            Password settings panel.
          </span>
        </TabsContent>
      </Tabs>
    </DemoSection>
  );
}

function OverlaysSection(): React.Node {
  const [lastAction, setLastAction] = useState('none');
  return (
    <DemoSection
      title="Dialog and DropdownMenu"
      description="dialog.tsx and dropdown-menu.tsx over the Radix shims over the top layer. The dialog's corners are square below 640px in the original — its source rounds them only at `sm:` — so the demo opts a phone in with a className."
      code={`<Dialog>
  <DialogTrigger asChild>
    <Button variant="outline">Open dialog</Button>
  </DialogTrigger>
  <DialogContent className="rounded-lg">
    <DialogHeader>
      <DialogTitle>shadcn dialog</DialogTitle>
      <DialogDescription>Top layer, focus-trapped.</DialogDescription>
    </DialogHeader>
    <DialogFooter>
      <DialogClose asChild><Button>Save</Button></DialogClose>
    </DialogFooter>
  </DialogContent>
</Dialog>

/* dialog.tsx ends "… duration-200 sm:rounded-lg": rounded only at ≥640px.
   The className above is how a phone opts in. */`}>
      <div className="flex flex-row flex-wrap gap-2">
        <Dialog>
          <DialogTrigger asChild>
            <Button className={TOUCH} variant="outline">
              Open dialog
            </Button>
          </DialogTrigger>
          <DialogContent className="rounded-lg">
            <DialogHeader>
              <DialogTitle>shadcn dialog</DialogTitle>
              <DialogDescription>
                dialog.tsx over the Radix shim over the top layer.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter>
              {/* A footer button closes the dialog by BEING a
                  DialogClose — Radix's asChild composition, not an
                  onClick that reaches for the open state. */}
              <DialogClose asChild>
                <Button className={TOUCH} onClick={() => setLastAction('save')}>
                  Save
                </Button>
              </DialogClose>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className={TOUCH} variant="secondary">
              Menu
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>Actions</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              className="min-h-11"
              onSelect={() => setLastAction('copy')}>
              Copy
            </DropdownMenuItem>
            <DropdownMenuItem
              className="min-h-11"
              onSelect={() => setLastAction('share')}>
              Share
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      <span className="mt-2 block text-sm text-muted-foreground">
        Last action: {lastAction}
      </span>
    </DemoSection>
  );
}

function AccordionSection(): React.Node {
  return (
    <DemoSection
      title="Accordion"
      description="Single type, collapsible; the chevron rotates through a data-[state=open] transform rule."
      code={`<Accordion type="single" collapsible>
  <AccordionItem value="a">
    <AccordionTrigger>Is it accessible?</AccordionTrigger>
    <AccordionContent>Yes — the shims carry the aria surface.</AccordionContent>
  </AccordionItem>
</Accordion>`}>
      {/*
        * `text-foreground` because the accordion is the one component here that
        * INHERITS its colour instead of setting one. On the web it inherits from
        * `body`, which shadcn's base layer gives `bg-background text-foreground`
        * — and that layer is deliberately not installed here, because its
        * preflight reset fights the user-agent styles. So the trigger fell back
        * to a colour that does not follow the scheme, and in dark mode it was
        * dark text on a dark page: the rows were there, and invisible.
        */}
      <Accordion className="text-foreground" type="single" collapsible={true}>
        <AccordionItem value="a">
          <AccordionTrigger className="min-h-11">
            Is it accessible?
          </AccordionTrigger>
          <AccordionContent>
            Yes — the shims carry the aria surface.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="b">
          <AccordionTrigger className="min-h-11">
            Is it styled?
          </AccordionTrigger>
          <AccordionContent>
            By its own Tailwind classes, resolved by the fork.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </DemoSection>
  );
}


/*
 * shadcn's base layer applies `bg-background text-foreground` to <body>. There
 * is no <body> here, so the screen root carries the half that matters.
 *
 * Every component that states its own text colour was fine without it, which
 * is why this went unnoticed: the ones that INHERIT — `outline` and `ghost`
 * buttons, the form labels, the dialog trigger — fell back to the platform's
 * default instead of the theme's, and in dark mode that is dark text on a
 * dark page. Preflight's `button { color: inherit }` is the other half; it
 * cancels the user-agent colour, and this supplies what replaces it.
 */
function Themed({children}: {children: React.Node}): React.Node {
  /* $FlowExpectedError[not-a-component] intrinsic <div> tag */
  return <div className="text-foreground">{children}</div>;
}

export default {
  title: 'shadcn/ui',
  category: 'UI',
  description:
    'Vendored, unmodified shadcn/ui components: Tailwind classes through ' +
    'the stylesheet engine, Radix primitives through the shims, markup ' +
    'through the intrinsics runtime.',
  examples: [
    {
      name: 'buttons',
      title: 'Button',
      render: (): React.Node => (
        <Themed>
          <ButtonsSection />
        </Themed>
      ),
    },
    {
      name: 'badge',
      title: 'Badge',
      render: (): React.Node => (
        <Themed>
          <BadgeSection />
        </Themed>
      ),
    },
    {
      name: 'card',
      title: 'Card',
      render: (): React.Node => (
        <Themed>
          <CardSection />
        </Themed>
      ),
    },
    {
      name: 'alert',
      title: 'Alert',
      render: (): React.Node => (
        <Themed>
          <AlertSection />
        </Themed>
      ),
    },
    {
      name: 'controls',
      title: 'Form controls',
      render: (): React.Node => (
        <Themed>
          <FormControlsSection />
        </Themed>
      ),
    },
    {
      name: 'progress',
      title: 'Progress, Skeleton, Toggle',
      render: (): React.Node => (
        <Themed>
          <ProgressSection />
        </Themed>
      ),
    },
    {
      name: 'tabs',
      title: 'Tabs',
      render: (): React.Node => (
        <Themed>
          <TabsSection />
        </Themed>
      ),
    },
    {
      name: 'overlays',
      title: 'Dialog and DropdownMenu',
      render: (): React.Node => (
        <Themed>
          <OverlaysSection />
        </Themed>
      ),
    },
    {
      name: 'accordion',
      title: 'Accordion',
      render: (): React.Node => (
        <Themed>
          <AccordionSection />
        </Themed>
      ),
    },
  ],
} as RNTesterModule;
