/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 * @format
 */

/**
 * Lists and their markers (css-lists-3 §3).
 *
 * Markers are generated by the list container rather than the item, because a
 * marker's text depends on the item's position among its siblings and a shadow
 * node has no parent pointer. The cases below cover every counter style we
 * implement, both `list-style-position` values, `<ol start>`, and nesting.
 */

import type {RNTesterModule} from '../../types/RNTesterTypes';

import {CodeBlock, DemoContent} from '../TextChildren/TextChildrenShared';
import * as React from 'react';
import {View} from 'react-native';

// A long item, so wrapping is visible: `outside` hangs the continuation lines
// past the marker, `inside` aligns them under it.
const LONG =
  'a deliberately long item so that it wraps onto a second line, which is ' +
  'where the two list-style-position values visibly differ';

function List({
  ordered,
  listStyleType,
  listStylePosition,
  start,
  items,
}: {
  ordered?: boolean,
  listStyleType?: string,
  listStylePosition?: string,
  start?: number,
  items: Array<string>,
}): React.Node {
  const style = {listStyleType, listStylePosition};
  return ordered === true ? (
    // $FlowExpectedError[not-a-component] intrinsic <ol> tag
    <ol style={style} start={start}>
      {items.map((text, i) => (
        // $FlowExpectedError[not-a-component] intrinsic <li> tag
        <li key={String(i)}>{text}</li>
      ))}
    </ol>
  ) : (
    // $FlowExpectedError[not-a-component] intrinsic <ul> tag
    <ul style={style}>
      {items.map((text, i) => (
        // $FlowExpectedError[not-a-component] intrinsic <li> tag
        <li key={String(i)}>{text}</li>
      ))}
    </ul>
  );
}

export default {
  title: 'Lists',
  category: 'Basic',
  description:
    'List markers and indentation per css-lists-3 §3: the counter styles, ' +
    'both list-style-position values, <ol start>, and nesting.',
  examples: [
    {
      name: 'baseline',
      title: 'Baseline alignment of an atomic inline',
      description:
        'An atomic inline box — inline-block, inline-flex, an <img> — is ' +
        'baseline-aligned by default. Its baseline here is its bottom border ' +
        'edge, so that edge should sit ON the text baseline, and the line has ' +
        'to stay tall enough for the text’s descender BELOW it. The text is ' +
        'all x-height characters, so the bottom of the glyphs is the ' +
        'baseline; the box bottom should line up with it exactly.',
      render: (): React.Node => (
        <DemoContent
          code={
            "<View style={{display: 'block'}}>\n" +
            "  {'xxx '}\n" +
            "  <span style={{display: 'inline-block', width: 24, height: 40,\n" +
            "                backgroundColor: '#c33'}} />\n" +
            "  {' xxx'}\n" +
            '</View>'
          }>
          <View style={{gap: 10}}>
            <View style={{display: 'block'}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  width: 24,
                  height: 40,
                  backgroundColor: '#c33',
                }}
              />
              {' xxx'}
            </View>
            {/* With in-flow text the baseline is that text's, not the bottom
                edge (CSS2 §10.8.1): the inner glyphs must sit on the SAME
                baseline as the outer ones. */}
            <View style={{display: 'block'}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  paddingHorizontal: 4,
                  paddingTop: 16,
                  backgroundColor: '#39c',
                }}>
                {'xxx'}
              </span>
              {' xxx'}
            </View>
            {/* A third offset, deliberately unlike the other two: padding
                BELOW the text pushes the box's baseline well above its bottom
                edge. Two probes cannot tell a correct formula from a wrong one
                when one of them has a zero offset — the empty box's baseline IS
                its bottom edge, so every candidate agrees on it. */}
            <View style={{display: 'block'}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  paddingHorizontal: 4,
                  paddingBottom: 24,
                  backgroundColor: '#7a3',
                }}>
                {'xxx'}
              </span>
              {' xxx'}
            </View>
            {/* The case that actually stresses the placement: a box SHORTER
                than the text beside it. In the probes above the box is the
                tallest thing on its line, so its top coincides with the line
                fragment's top and several different formulas would agree by
                accident. Here the text sets the line's ascent instead. */}
            {/* $FlowExpectedError[incompatible-type] `fontSize` on a View is
                honoured at runtime — text attributes cascade to text children —
                but ViewStyle does not model inherited text properties yet.
                DOM-CSS-LIMITATION(view-style-text-inheritance) */}
            <View style={{display: 'block', fontSize: 40}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  width: 10,
                  height: 10,
                  backgroundColor: '#93c',
                }}
              />
              {' xxx'}
            </View>
            {/* Both at once: shorter than the line AND a non-zero baseline
                offset. The two cases above each vary only one of those, so
                each still leaves one term of the placement untested. */}
            {/* $FlowExpectedError[incompatible-type] `fontSize` on a View is
                honoured at runtime — text attributes cascade to text children —
                but ViewStyle does not model inherited text properties yet.
                DOM-CSS-LIMITATION(view-style-text-inheritance) */}
            <View style={{display: 'block', fontSize: 40}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  fontSize: 10,
                  paddingHorizontal: 4,
                  paddingBottom: 6,
                  backgroundColor: '#c39',
                }}>
                {'xxx'}
              </span>
              {' xxx'}
            </View>
            {/* overflow other than `visible` is the rule's second escape hatch
                (CSS2 §10.8.1): the box aligns by its bottom edge whatever its
                content, because a clipped line box is not something you can
                sensibly align a line to. This pink box has the SAME content and
                padding as the one above it, so the only thing that may move it
                is the overflow. Its bottom should sit on the baseline. */}
            <View style={{display: 'block'}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <span> tag */}
              <span
                style={{
                  display: 'inline-block',
                  paddingHorizontal: 4,
                  paddingBottom: 24,
                  overflow: 'hidden',
                  backgroundColor: '#f80',
                }}>
                {'xxx'}
              </span>
              {' xxx'}
            </View>
            {/* A replaced element. CSS2 §10.8.1 gives an inline replaced box
                the same treatment as a box with no line boxes: its baseline is
                its bottom margin edge, so the image's bottom should sit on the
                text baseline exactly as the empty red box does. A data URI so
                the probe never depends on the network. */}
            <View style={{display: 'block'}}>
              {'xxx '}
              {/* $FlowExpectedError[not-a-component] intrinsic <img> tag */}
              <img
                source={{
                  uri:
                    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB' +
                    'CAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
                }}
                style={{width: 30, height: 30, backgroundColor: '#333'}}
              />
              {' xxx'}
            </View>
          </View>
        </DemoContent>
      ),
    },
    {
      name: 'bullets',
      title: 'Unordered: the UA bullet, and what nesting does to it',
      description:
        'An unauthored <ul> takes the bullet for its depth — disc, then ' +
        'circle, then square — which is the ul/ul/ul chain a UA stylesheet ' +
        'spells out, resolved here from nesting depth because an item cannot ' +
        'walk its ancestors.',
      render: (): React.Node => (
        <DemoContent
          code={
            '<ul>\n' +
            '  <li>disc at the top level</li>\n' +
            '  <li>\n' +
            '    <ul><li>circle one level in</li>\n' +
            '      <ul><li>square two levels in</li></ul>\n' +
            '    </ul>\n' +
            '  </li>\n' +
            '</ul>'
          }>
          {/* $FlowExpectedError[not-a-component] intrinsic <ul> tag */}
          <ul>
            {/* $FlowExpectedError[not-a-component] */}
            <li>disc at the top level</li>
            {/* $FlowExpectedError[not-a-component] */}
            <li>
              still disc
              {/* $FlowExpectedError[not-a-component] */}
              <ul>
                {/* $FlowExpectedError[not-a-component] */}
                <li>circle one level in</li>
                {/* $FlowExpectedError[not-a-component] */}
                <ul>
                  {/* $FlowExpectedError[not-a-component] */}
                  <li>square two levels in</li>
                </ul>
              </ul>
            </li>
          </ul>
        </DemoContent>
      ),
    },
    {
      name: 'types',
      title: 'list-style-type on an unordered list',
      description:
        'disc, circle, square and none. An unknown keyword falls back the ' +
        'way a UA does with a value it has not implemented.',
      render: (): React.Node => (
        <DemoContent code={"<ul style={{listStyleType: 'square'}}>…</ul>"}>
          <View style={{gap: 8}}>
            <List items={['disc (the default)']} />
            <List listStyleType="circle" items={['circle']} />
            <List listStyleType="square" items={['square']} />
            <List listStyleType="none" items={['none — indented, no marker']} />
          </View>
        </DemoContent>
      ),
    },
    {
      name: 'ordered',
      title: 'Ordered: counters, and where they start',
      description:
        'decimal is the default. <ol start> seeds the counter, exactly as ' +
        'the HTML attribute does.',
      render: (): React.Node => (
        <DemoContent
          code={'<ol start={8}>\n  <li>eight</li>\n  <li>nine</li>\n</ol>'}>
          <View style={{gap: 8}}>
            <List ordered items={['one', 'two', 'three']} />
            <List ordered start={8} items={['eight', 'nine', 'ten']} />
          </View>
        </DemoContent>
      ),
    },
    {
      name: 'counters',
      title: 'Alphabetic and Roman counter styles',
      description:
        'lower-alpha carries bijectively — z is followed by aa, not a0 — and ' +
        'the Roman styles use the subtractive pairs, so 4 is IV rather than ' +
        'IIII.',
      render: (): React.Node => (
        <DemoContent code={"<ol style={{listStyleType: 'upper-roman'}}>…</ol>"}>
          <View style={{gap: 8}}>
            <List ordered listStyleType="lower-alpha" items={['a', 'b', 'c']} />
            <List
              ordered
              listStyleType="lower-alpha"
              start={25}
              items={['y', 'z', 'aa — the carry']}
            />
            <List
              ordered
              listStyleType="upper-roman"
              items={['I', 'II', 'III', 'IV — subtractive', 'V']}
            />
          </View>
        </DemoContent>
      ),
    },
    {
      name: 'position',
      title: 'list-style-position: two mechanisms, not an offset',
      description:
        'outside is the CSS initial value: the marker is NOT measured with ' +
        'the content, so it hangs in the gutter and every line — wrapped ' +
        'ones included — starts at the content edge. inside makes the marker ' +
        'part of the measured content, so a wrapped line aligns under it. ' +
        'Watch the second line of each item.',
      render: (): React.Node => (
        <DemoContent
          code={
            "<ul style={{listStylePosition: 'outside'}}>  // the default\n" +
            "<ul style={{listStylePosition: 'inside'}}>"
          }>
          <View style={{gap: 12}}>
            <List items={[LONG]} />
            <List listStylePosition="inside" items={[LONG]} />
          </View>
        </DemoContent>
      ),
    },
    {
      name: 'markerStyle',
      title: 'The marker takes the item’s own text styling',
      description:
        'A marker is generated content of the item, so it inherits the ' +
        'item’s font and colour rather than being drawn in some fixed style.',
      render: (): React.Node => (
        <DemoContent code={"<li style={{color: '#0a7', fontSize: 20}}>…</li>"}>
          {/* $FlowExpectedError[not-a-component] intrinsic <ul> tag */}
          <ul>
            {/* $FlowExpectedError[not-a-component] */}
            <li style={{color: '#0a7', fontSize: 20}}>
              a large green item, marker included
            </li>
            {/* $FlowExpectedError[not-a-component] */}
            <li style={{color: '#c33'}}>a red one</li>
          </ul>
        </DemoContent>
      ),
    },
    {
      name: 'notImplemented',
      title: 'What is not implemented',
      render: (): React.Node => (
        <DemoContent>
          <CodeBlock
            code={
              '// DOM-CSS-LIMITATION(list-style-type-additive-scripts)\n' +
              'The predefined numeric and alphabetic styles are all\n' +
              'here (arabic-indic, devanagari, thai, cjk-decimal,\n' +
              'lower-greek, hiragana, katakana, …). Still missing:\n' +
              'the additive scripts (armenian, georgian, hebrew) and\n' +
              'the complex styles of §7 (japanese-*, korean-*,\n' +
              'ethiopic-numeric). An unknown keyword falls back\n' +
              'rather than breaking.\n\n' +
              '// @counter-style is stylesheet machinery, not renderer.\n' +
              '// list-style-image and ::marker are not implemented.'
            }
          />
        </DemoContent>
      ),
    },
  ],
} as RNTesterModule;
