/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @noflow
 * @format
 */

// GENERATED by text-conformance/gen-device-screen.js — do not edit by hand.
// Edit text-conformance/cases.js and regenerate.
//
// @noflow rather than strict-local: the corpus sets inheritable text
// properties (fontSize) on Views, which is exactly what this feature adds and
// exactly what ViewStyle does not yet describe, and it builds elements from
// data, so every tag is a computed string. Typing generated fixture data buys
// nothing the corpus does not already check by measurement.

import * as React from 'react';
import {ScrollView, Text, View} from 'react-native';

import '@react-native/expo-intrinsics-poc';

const W = 320;
const FS = 16;

const CASES = [
 {
  "name": "block-splits-run",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "before",
    "tag": "span",
    "children": [
     "before"
    ]
   },
   {
    "id": "blk",
    "tag": "div",
    "style": {
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "after",
    "tag": "span",
    "children": [
     "after"
    ]
   }
  ]
 },
 {
  "name": "block-first-then-text",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "blk",
    "tag": "div",
    "style": {
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "after",
    "tag": "span",
    "children": [
     "after"
    ]
   }
  ]
 },
 {
  "name": "text-then-block-last",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "before",
    "tag": "span",
    "children": [
     "before"
    ]
   },
   {
    "id": "blk",
    "tag": "div",
    "style": {
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "two-blocks-three-runs",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "t1",
    "tag": "span",
    "children": [
     "one"
    ]
   },
   {
    "id": "b1",
    "tag": "div",
    "style": {
     "height": 8,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "t2",
    "tag": "span",
    "children": [
     "two"
    ]
   },
   {
    "id": "b2",
    "tag": "div",
    "style": {
     "height": 8,
     "backgroundColor": "#f4a261"
    }
   },
   {
    "id": "t3",
    "tag": "span",
    "children": [
     "three"
    ]
   }
  ]
 },
 {
  "name": "inline-siblings-survive-the-split",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "b",
    "children": [
     "bold"
    ]
   },
   " plain ",
   {
    "id": "b",
    "tag": "i",
    "children": [
     "ital"
    ]
   },
   {
    "id": "blk",
    "tag": "div",
    "style": {
     "height": 8,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "c",
    "tag": "span",
    "children": [
     "tail"
    ]
   }
  ]
 },
 {
  "name": "display-none-does-not-split",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "left"
    ]
   },
   {
    "tag": "div",
    "style": {
     "display": "none",
     "height": 30
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "right"
    ]
   }
  ]
 },
 {
  "name": "absolute-child-does-not-split-a-block",
  "container": {
   "display": "block",
   "position": "relative"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "left"
    ]
   },
   {
    "tag": "div",
    "style": {
     "position": "absolute",
     "top": 0,
     "right": 0,
     "width": 8,
     "height": 8,
     "backgroundColor": "#e76f51"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "right"
    ]
   }
  ]
 },
 {
  "name": "inline-padding-baseline",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-padding-inline-axis",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "paddingLeft": 10,
     "paddingRight": 10
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-padding-left-only",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "paddingLeft": 10
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-padding-right-only",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "paddingRight": 10
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-padding-inline-axis-large",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "paddingLeft": 40,
     "paddingRight": 40
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-border-inline-axis",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "borderLeftWidth": 4,
     "borderRightWidth": 4,
     "borderColor": "#e76f51",
     "borderStyle": "solid"
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "inline-block-axis-padding-does-not-grow-the-line",
  "container": {
   "display": "block"
  },
  "children": [
   "x ",
   {
    "id": "mid",
    "tag": "span",
    "style": {
     "paddingTop": 12,
     "paddingBottom": 12
    },
    "children": [
     "alpha beta"
    ]
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     " y"
    ]
   }
  ]
 },
 {
  "name": "nested-inlines",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "outer",
    "tag": "span",
    "children": [
     "out ",
     {
      "id": "inner",
      "tag": "b",
      "children": [
       "in"
      ]
     },
     " out"
    ]
   }
  ]
 },
 {
  "name": "inline-wrapping-across-lines",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "lead",
    "tag": "span",
    "children": [
     "lead "
    ]
   },
   {
    "id": "wrapped",
    "tag": "span",
    "children": [
     "wrapping text that is long enough to need more than one line in the box"
    ]
   }
  ]
 },
 {
  "name": "inline-block-sized-stays-in-the-line",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "before "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 24,
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     " after"
    ]
   }
  ]
 },
 {
  "name": "inline-flex-sized-stays-in-the-line",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "before "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-flex",
     "width": 24,
     "height": 12,
     "backgroundColor": "#2a9d8f"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     " after"
    ]
   }
  ]
 },
 {
  "name": "inline-flex-lays-out-its-children-as-flex-items",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "before "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-flex",
     "height": 14
    },
    "children": [
     {
      "id": "f1",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#6ea8fe"
      }
     },
     {
      "id": "f2",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#f4a261"
      }
     }
    ]
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     " after"
    ]
   }
  ]
 },
 {
  "name": "inline-block-wraps-its-own-text",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "before "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 80,
     "backgroundColor": "#eef2ff"
    },
    "children": [
     "wrapping text that is long enough to need more than one line in the box"
    ]
   }
  ]
 },
 {
  "name": "atomic-inline-between-two-runs-does-not-split-them",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "left "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 12,
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     " right"
    ]
   }
  ]
 },
 {
  "name": "flex-row-items-sit-side-by-side",
  "container": {
   "display": "flex",
   "flexDirection": "row"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "one"
    ]
   },
   {
    "id": "mid",
    "tag": "div",
    "style": {
     "width": 12,
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "two"
    ]
   }
  ]
 },
 {
  "name": "flex-column-stacks-items",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "one"
    ]
   },
   {
    "id": "mid",
    "tag": "div",
    "style": {
     "width": 12,
     "height": 12,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "two"
    ]
   }
  ]
 },
 {
  "name": "flex-anonymous-item-baseline",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   "one ",
   "two",
   {
    "id": "marker",
    "tag": "div",
    "style": {
     "width": 10,
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "flex-display-none-does-not-split-a-run",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   "one ",
   {
    "tag": "div",
    "style": {
     "display": "none",
     "width": 12,
     "height": 12
    }
   },
   "two",
   {
    "id": "marker",
    "tag": "div",
    "style": {
     "width": 10,
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "flex-block-child-splits-a-run",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   "one ",
   {
    "id": "sep",
    "tag": "div",
    "style": {
     "height": 6,
     "backgroundColor": "#f4a261"
    }
   },
   "two",
   {
    "id": "marker",
    "tag": "div",
    "style": {
     "width": 10,
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "flex-absolute-child-splits-a-run-sequence",
  "container": {
   "display": "flex",
   "flexDirection": "column",
   "position": "relative"
  },
  "children": [
   "one ",
   {
    "tag": "div",
    "style": {
     "position": "absolute",
     "top": 0,
     "right": 0,
     "width": 8,
     "height": 8,
     "backgroundColor": "#e76f51"
    }
   },
   "two",
   {
    "id": "marker",
    "tag": "div",
    "style": {
     "width": 10,
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "flex-blockifies-an-inline-child",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "style": {
     "display": "inline"
    },
    "children": [
     "one"
    ]
   },
   {
    "id": "b",
    "tag": "span",
    "style": {
     "display": "inline"
    },
    "children": [
     "two"
    ]
   }
  ]
 },
 {
  "name": "flex-blockifies-inline-flex-to-flex",
  "container": {
   "display": "flex",
   "flexDirection": "column"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "above"
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-flex",
     "height": 14
    },
    "children": [
     {
      "id": "f1",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#6ea8fe"
      }
     },
     {
      "id": "f2",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#f4a261"
      }
     }
    ]
   }
  ]
 },
 {
  "name": "flex-inside-block-between-two-runs",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "above"
    ]
   },
   {
    "id": "flex",
    "tag": "div",
    "style": {
     "display": "flex",
     "flexDirection": "row",
     "height": 14
    },
    "children": [
     {
      "id": "f1",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#6ea8fe"
      }
     },
     {
      "id": "f2",
      "tag": "div",
      "style": {
       "width": 10,
       "height": 10,
       "backgroundColor": "#f4a261"
      }
     }
    ]
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "below"
    ]
   }
  ]
 },
 {
  "name": "block-inside-block-with-text-either-side",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "above"
    ]
   },
   {
    "id": "outer",
    "tag": "div",
    "style": {
     "display": "block"
    },
    "children": [
     {
      "id": "inner",
      "tag": "span",
      "children": [
       "nested"
      ]
     }
    ]
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "below"
    ]
   }
  ]
 },
 {
  "name": "inline-flex-inside-an-inline",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "outer",
    "tag": "span",
    "children": [
     "a ",
     {
      "id": "box",
      "tag": "div",
      "style": {
       "display": "inline-flex",
       "width": 14,
       "height": 10,
       "backgroundColor": "#2a9d8f"
      }
     },
     " b"
    ]
   }
  ]
 },
 {
  "name": "three-runs-around-two-atomic-inlines",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "a "
    ]
   },
   {
    "id": "x",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 10,
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     " b "
    ]
   },
   {
    "id": "y",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 10,
     "height": 10,
     "backgroundColor": "#f4a261"
    }
   },
   {
    "id": "c",
    "tag": "span",
    "children": [
     " c"
    ]
   }
  ]
 },
 {
  "name": "block-splits-a-run-that-was-already-wrapping",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "wrapping text that is long enough to need more than one line in the box"
    ]
   },
   {
    "id": "blk",
    "tag": "div",
    "style": {
     "height": 8,
     "backgroundColor": "#6ea8fe"
    }
   },
   {
    "id": "b",
    "tag": "span",
    "children": [
     "tail"
    ]
   }
  ]
 },
 {
  "name": "inline-block-containing-a-block",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "a",
    "tag": "span",
    "children": [
     "before "
    ]
   },
   {
    "id": "box",
    "tag": "div",
    "style": {
     "display": "inline-block",
     "width": 60,
     "backgroundColor": "#eef2ff"
    },
    "children": [
     {
      "id": "inner",
      "tag": "div",
      "style": {
       "height": 8,
       "backgroundColor": "#6ea8fe"
      }
     }
    ]
   }
  ]
 },
 {
  "name": "rect-of-an-inline-with-no-decorations",
  "container": {
   "display": "block"
  },
  "children": [
   "lead ",
   {
    "id": "probe",
    "tag": "span",
    "children": [
     "measured"
    ]
   }
  ]
 },
 {
  "name": "rect-of-an-empty-inline",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "lead",
    "tag": "span",
    "children": [
     "lead"
    ]
   },
   {
    "id": "probe",
    "tag": "span",
    "children": []
   },
   {
    "id": "tail",
    "tag": "span",
    "children": [
     "tail"
    ]
   }
  ]
 },
 {
  "name": "rect-of-a-padded-inline-is-the-border-box",
  "container": {
   "display": "block"
  },
  "children": [
   "lead ",
   {
    "id": "probe",
    "tag": "span",
    "style": {
     "paddingLeft": 6,
     "paddingRight": 6,
     "paddingTop": 3,
     "paddingBottom": 3
    },
    "children": [
     "measured"
    ]
   }
  ]
 },
 {
  "name": "rect-of-a-block-is-the-content-width",
  "container": {
   "display": "block"
  },
  "children": [
   {
    "id": "probe",
    "tag": "div",
    "style": {
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 },
 {
  "name": "rect-inside-a-padded-container",
  "container": {
   "display": "block",
   "padding": 12
  },
  "children": [
   {
    "id": "probe",
    "tag": "div",
    "style": {
     "height": 10,
     "backgroundColor": "#6ea8fe"
    }
   }
  ]
 }
];

/**
 * Renders one node of a case. A bare string stays a bare string — wrapping it
 * would turn anonymous text into an element and change the very thing several
 * cases are about.
 */
function renderNode(node, register, key) {
  if (typeof node === 'string') {
    return node;
  }
  const children = (node.children ?? []).map((child, i) =>
    renderNode(child, register, key + '.' + String(i)),
  );
  const props = {key};
  if (node.style != null) {
    props.style = node.style;
  }
  if (node.id != null) {
    const id = node.id;
    props.ref = instance => {
      register(id, instance);
    };
  }
  return React.createElement(node.tag, props, ...children);
}

function relativeRect(node, base) {
  if (node == null || base == null || typeof node.getBoundingClientRect !== 'function') {
    return null;
  }
  const r = node.getBoundingClientRect();
  const b = base.getBoundingClientRect();
  return {x: r.x - b.x, y: r.y - b.y, w: r.width, h: r.height};
}

function CaseView({item}) {
  const containerRef = React.useRef(null);
  const probes = React.useRef({}).current;

  const register = React.useCallback(
    (id, instance) => {
      probes[id] = instance;
    },
    [probes],
  );

  React.useEffect(() => {
    const publish = () => {
      const base = containerRef.current;
      if (base == null || typeof base.getBoundingClientRect !== 'function') {
        return;
      }
      const b = base.getBoundingClientRect();
      const measured = {
        container: {x: 0, y: 0, w: b.width, h: b.height},
        probes: {},
      };
      for (const id of Object.keys(probes)) {
        const rect = relativeRect(probes[id], base);
        if (rect != null) {
          measured.probes[id] = rect;
        }
      }
      const all = globalThis.__textConformance ?? {};
      all[item.name] = measured;
      globalThis.__textConformance = all;
    };
    // Twice: once when layout has settled, once more in case anything that
    // measures text asynchronously moved it after the first pass.
    const t1 = setTimeout(publish, 600);
    const t2 = setTimeout(publish, 2200);
    return () => {
      clearTimeout(t1);
      clearTimeout(t2);
    };
  }, [item, probes]);

  return (
    <View style={styles.caseWrapper}>
      <Text style={styles.caseName}>{item.name}</Text>
      <View
        ref={containerRef}
        style={[styles.container, {width: W, fontSize: FS}, item.container]}>
        {item.children.map((child, i) => renderNode(child, register, String(i)))}
      </View>
    </View>
  );
}

function TextConformanceScreen() {
  return (
    <ScrollView style={styles.scroll}>
      {CASES.map(item => (
        <CaseView key={item.name} item={item} />
      ))}
    </ScrollView>
  );
}

// The dashed outline lives on the WRAPPER, never on the measured container:
// probe rects are container-border-box relative, so a border there would shift
// every one of them by its width — and the web page draws its own with
// `outline`, which does not affect layout at all.
const styles = {
  scroll: {flex: 1, backgroundColor: '#f8fafc'},
  caseWrapper: {
    margin: 8,
    padding: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
    alignSelf: 'flex-start',
  },
  caseName: {fontSize: 10, color: '#64748b', marginBottom: 4},
  // Black on white, like the oracle page: the corpus is about geometry, and a
  // theme that hides the text hides whether the geometry is describing it.
  container: {color: '#000000'},
};

export default {
  title: 'Text conformance',
  category: 'Basic',
  description:
    'Mixed inline / block / flex / inline-flex layout, pinned against real Safari. ' +
    'Publishes getBoundingClientRect() to globalThis.__textConformance for ' +
    'text-conformance/verify.js.',
  examples: [
    {
      title: 'Cases',
      render: () => <TextConformanceScreen />,
    },
  ],
};
