/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @noflow
 * @format
 */

'use strict';

/**
 * GENERATED by text-conformance/gen-device-screen.js — do not edit.
 *
 * Renders the conformance corpus and reports every measured box's rect,
 * relative to its own case root, to the harness on :8900. The browser side of
 * the same corpus is `expected.json`; `verify.js` compares them.
 *
 * Rects are reported relative to the case root so that a difference means a
 * layout difference. An absolute coordinate would also carry the screen's
 * padding, the scroll offset and the status bar, and a constant offset in all
 * of those looks exactly like a real bug.
 */

import {TERTIARY_COLOR} from './themed';
import * as React from 'react';
import {useCallback, useEffect, useRef, useState} from 'react';
import {ScrollView, Text, View} from 'react-native';

import '@react-native/expo-intrinsics-poc';

const REPORT_URL = 'http://localhost:8900/report';

const CORPUS = [
  {
    name: 'atomic-inlines-in-a-row',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'a',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
        {
          tag: 'span',
          m: 'b',
          style: {
            display: 'inline-block',
            width: '60px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
        {
          tag: 'span',
          m: 'c',
          style: {
            display: 'inline-block',
            width: '30px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#ff9500',
          },
        },
      ],
    },
  },
  {
    name: 'atomic-inlines-wrap',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'a',
          style: {
            display: 'inline-block',
            width: '100px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
        {
          tag: 'span',
          m: 'b',
          style: {
            display: 'inline-block',
            width: '100px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#ff3b30',
          },
        },
        {
          tag: 'span',
          m: 'c',
          style: {
            display: 'inline-block',
            width: '100px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#30b0c7',
          },
        },
        {
          tag: 'span',
          m: 'd',
          style: {
            display: 'inline-block',
            width: '100px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
      ],
    },
  },
  {
    name: 'atomic-inline-taller-than-line-height',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'tall',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '50px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
      ],
    },
  },
  {
    name: 'text-only-honours-line-height',
    withText: true,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: ['Ag'],
    },
  },
  {
    name: 'short-box-alone-honours-line-height',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'only',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '10px',
            verticalAlign: 'top',
            backgroundColor: '#ff9500',
          },
        },
      ],
    },
  },
  {
    name: 'line-height-is-a-floor-not-a-ceiling',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'shortA',
          style: {
            display: 'inline-block',
            width: '200px',
            height: '10px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
        {
          tag: 'span',
          m: 'shortB',
          style: {
            display: 'inline-block',
            width: '200px',
            height: '10px',
            verticalAlign: 'top',
            backgroundColor: '#ff3b30',
          },
        },
      ],
    },
  },
  {
    name: 'a-tall-line-pushes-the-next-line-down',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'tall',
          style: {
            display: 'inline-block',
            width: '200px',
            height: '50px',
            verticalAlign: 'top',
            backgroundColor: '#30b0c7',
          },
        },
        {
          tag: 'span',
          m: 'second',
          style: {
            display: 'inline-block',
            width: '200px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
      ],
    },
  },
  {
    name: 'nested-in-one-inline',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'before',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
        {
          tag: 'span',
          style: {},
          children: [
            {
              tag: 'span',
              m: 'inner',
              style: {
                display: 'inline-block',
                width: '40px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#ff9500',
              },
            },
          ],
        },
      ],
    },
  },
  {
    name: 'nested-three-deep',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'before',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
        {
          tag: 'span',
          style: {},
          children: [
            {
              tag: 'span',
              style: {},
              children: [
                {
                  tag: 'span',
                  style: {},
                  children: [
                    {
                      tag: 'span',
                      m: 'inner',
                      style: {
                        display: 'inline-block',
                        width: '40px',
                        height: '20px',
                        verticalAlign: 'top',
                        backgroundColor: '#ff3b30',
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    name: 'nested-then-sibling',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          style: {},
          children: [
            {
              tag: 'span',
              m: 'inner',
              style: {
                display: 'inline-block',
                width: '40px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#30b0c7',
              },
            },
          ],
        },
        {
          tag: 'span',
          m: 'after',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
      ],
    },
  },
  {
    name: 'inline-flex-atomic',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'before',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
        {
          tag: 'span',
          m: 'flex',
          style: {
            display: 'inline-flex',
            width: '80px',
            height: '20px',
            verticalAlign: 'top',
          },
          children: [
            {
              tag: 'span',
              m: 'flexchild',
              style: {
                display: 'inline-block',
                width: '20px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#ff9500',
              },
            },
          ],
        },
        {
          tag: 'span',
          m: 'after',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
      ],
    },
  },
  {
    name: 'inline-flex-lays-out-its-children',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'flex',
          style: {
            display: 'inline-flex',
            width: '120px',
            height: '30px',
            verticalAlign: 'top',
          },
          children: [
            {
              tag: 'span',
              m: 'i1',
              style: {
                display: 'inline-block',
                width: '30px',
                height: '30px',
                verticalAlign: 'top',
                backgroundColor: '#ff3b30',
              },
            },
            {
              tag: 'span',
              m: 'i2',
              style: {
                display: 'inline-block',
                width: '30px',
                height: '30px',
                verticalAlign: 'top',
                backgroundColor: '#30b0c7',
              },
            },
          ],
        },
      ],
    },
  },
  {
    name: 'empty-inline-between-boxes',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'a',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
        {
          tag: 'span',
          style: {},
          children: [],
        },
        {
          tag: 'span',
          m: 'b',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
      ],
    },
  },
  {
    name: 'inline-with-padding-around-box',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'before',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#ff9500',
          },
        },
        {
          tag: 'span',
          style: {
            paddingLeft: '10px',
            paddingRight: '10px',
          },
          children: [
            {
              tag: 'span',
              m: 'inner',
              style: {
                display: 'inline-block',
                width: '40px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#af52de',
              },
            },
          ],
        },
        {
          tag: 'span',
          m: 'after',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#ff3b30',
          },
        },
      ],
    },
  },
  {
    name: 'vertical-align-top-vs-default',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'short',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#30b0c7',
          },
        },
        {
          tag: 'span',
          m: 'tall',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '40px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
      ],
    },
  },
  {
    name: 'vertical-align-bottom',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'tall',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '40px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
        {
          tag: 'span',
          m: 'short',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'bottom',
            backgroundColor: '#ff9500',
          },
        },
      ],
    },
  },
  {
    name: 'vertical-align-middle',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'tall',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '40px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
        {
          tag: 'span',
          m: 'short',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'middle',
            backgroundColor: '#ff3b30',
          },
        },
      ],
    },
  },
  {
    name: 'baseline-aligned-box-alone',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'only',
          style: {
            display: 'inline-block',
            width: '30px',
            height: '40px',
            backgroundColor: '#0a84ff',
          },
        },
      ],
    },
  },
  {
    name: 'atomic-inline-alone-on-line',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'only',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '60px',
            verticalAlign: 'top',
            backgroundColor: '#30b0c7',
          },
        },
      ],
    },
  },
  {
    name: 'wrap-boundary-exact',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'a',
          style: {
            display: 'inline-block',
            width: '150px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#0a84ff',
          },
        },
        {
          tag: 'span',
          m: 'b',
          style: {
            display: 'inline-block',
            width: '150px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#34c759',
          },
        },
        {
          tag: 'span',
          m: 'c',
          style: {
            display: 'inline-block',
            width: '10px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#ff9500',
          },
        },
      ],
    },
  },
  {
    name: 'nested-inline-wrap',
    withText: false,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        {
          tag: 'span',
          m: 'a',
          style: {
            display: 'inline-block',
            width: '200px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#af52de',
          },
        },
        {
          tag: 'span',
          style: {},
          children: [
            {
              tag: 'span',
              m: 'inner',
              style: {
                display: 'inline-block',
                width: '150px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#ff3b30',
              },
            },
          ],
        },
      ],
    },
  },
  {
    name: 'box-between-text',
    withText: true,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        'before ',
        {
          tag: 'span',
          m: 'mid',
          style: {
            display: 'inline-block',
            width: '40px',
            height: '20px',
            verticalAlign: 'top',
            backgroundColor: '#30b0c7',
          },
        },
        ' after',
      ],
    },
  },
  {
    name: 'box-in-inline-with-text',
    withText: true,
    tree: {
      tag: 'div',
      m: 'root',
      style: {
        width: '300px',
        lineHeight: '20px',
        fontSize: '16px',
      },
      children: [
        'see ',
        {
          tag: 'span',
          style: {},
          children: [
            'link ',
            {
              tag: 'span',
              m: 'mid',
              style: {
                display: 'inline-block',
                width: '40px',
                height: '20px',
                verticalAlign: 'top',
                backgroundColor: '#0a84ff',
              },
            },
            ' end',
          ],
        },
        ' done',
      ],
    },
  },
];

/*
 * The corpus writes CSS lengths as strings ("40px") because that is what the
 * browser side needs. React Native takes numbers, so they are converted here
 * rather than stored twice — one corpus, two consumers.
 */
function toStyle(css) {
  const out = {};
  for (const [key, value] of Object.entries(css ?? {})) {
    if (typeof value === 'string' && /^-?\d+(\.\d+)?px$/.test(value)) {
      out[key] = parseFloat(value);
    } else {
      out[key] = value;
    }
  }
  return out;
}

function render(node, refs, key) {
  if (typeof node === 'string') {
    return node;
  }
  const Tag = node.tag;
  const children = (node.children ?? []).map((child, i) =>
    render(child, refs, i),
  );
  const props = {key, style: toStyle(node.style)};
  if (node.m != null) {
    props.ref = instance => {
      if (instance != null) {
        refs.current[node.m] = instance;
      }
    };
  }
  return React.createElement(
    Tag,
    props,
    children.length ? children : undefined,
  );
}

function Case({caseData, onMeasured}) {
  const refs = useRef({});

  const measure = useCallback(() => {
    const rootInstance = refs.current.root;
    if (rootInstance == null) {
      return;
    }
    const rootRect = rootInstance.getBoundingClientRect();
    const rects = {};
    for (const [m, instance] of Object.entries(refs.current)) {
      const r = instance?.getBoundingClientRect?.();
      if (r == null) {
        continue;
      }
      rects[m] = {
        x: Number((r.x - rootRect.x).toFixed(2)),
        y: Number((r.y - rootRect.y).toFixed(2)),
        width: Number(r.width.toFixed(2)),
        height: Number(r.height.toFixed(2)),
      };
    }
    onMeasured(caseData.name, rects);
  }, [caseData.name, onMeasured]);

  useEffect(() => {
    // One frame after mount: layout has to have run before a rect means
    // anything, and the images/controls in some cases resolve a frame later.
    const id = setTimeout(measure, 350);
    return () => clearTimeout(id);
  }, [measure]);

  return (
    <View style={{marginBottom: 24}}>
      <Text style={{fontSize: 10, color: TERTIARY_COLOR}}>{caseData.name}</Text>
      {render(caseData.tree, refs, caseData.name)}
    </View>
  );
}

function ConformanceScreen() {
  const results = useRef({});
  const [status, setStatus] = useState(`measuring ${CORPUS.length} cases…`);

  const onMeasured = useCallback((name, rects) => {
    results.current[name] = rects;
    if (Object.keys(results.current).length !== CORPUS.length) {
      return;
    }
    /*
     * The report is best-effort, and NOT reaching the harness is the normal
     * case.
     *
     * This screen is useful on its own — it is the corpus, rendered — and most
     * of the time nobody is running verify.js to receive the geometry. Showing
     * "report failed: Network request failed" then was wrong twice over: it put
     * an error on a screen that had done nothing wrong, and it trained the eye
     * to ignore the one line that would matter if a real failure appeared.
     */
    fetch(REPORT_URL, {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify(results.current),
    })
      .then(() => setStatus(`reported ${CORPUS.length} cases to the harness`))
      .catch(() =>
        setStatus(
          `${CORPUS.length} cases measured · harness not listening on :8900`,
        ),
      );
  }, []);

  return (
    <ScrollView contentContainerStyle={{padding: 8}}>
      <Text style={{fontSize: 11, color: TERTIARY_COLOR, marginBottom: 8}}>
        {status}
      </Text>
      {CORPUS.map(c => (
        <Case key={c.name} caseData={c} onMeasured={onMeasured} />
      ))}
    </ScrollView>
  );
}

export default {
  title: 'HTML: conformance harness',
  category: 'UI',
  description:
    'Renders the text-conformance corpus and reports its geometry to the ' +
    'harness for comparison with real Safari.',
  examples: [
    {
      name: 'conformance',
      title: 'Corpus',
      render: () => <ConformanceScreen />,
    },
  ],
};
